ci: error and exit if repo data artifact not found

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -165,6 +165,9 @@ jobs:
             echo "::group::Display resulting directory structure"
             ls --almost-all --recursive --ignore node_modules --ignore .git
             echo "::endgroup::"
+          else
+            echo "::error ::Data file '$REPO_JSON_FILE' not found."
+            exit 1
           fi
       - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
         if: fromJSON(steps.sem-rel.outputs.new-release-published)
